### ISSUE TITLE
connect urls between the HTML pages

### ISSUE THREAD

**Issue by sadiaanzum** [RuohanSong/EcoTech#11]
Unable to connect urls between pages. For example, clicking on links in header and footer, and redirecting to the respective html page. Check views.py and urls.py and also inline html links.

**Comment by RuohanSong** [comment]
urls.py and views.py updated to show pages correctly

**Comment by RuohanSong** [comment]
media directory added, MEDIA_URL and MEDIA_ROOT added in settings.py, urlpatterns updated in urls.py so that images can be displayed properly;

about.html, contact.html, FAQ.html, and home.html pages updated to use base.html templates correctly such that all the pages are inheriting the navbar and footer from the base.html template.

However, there are still some issues to be fixed:
1. the logo.jpg image size is not correct
2. the benefits section design has been changed.

**Comment by RuohanSong** [comment]
New found issues:
3. In contact page, navbar font color is same as the background so that the navbar is invisible
4. FAQ page format needs to be fixed
